### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by AryanJ-NYC** [yvanpdev/Knapsack#7]
## Story
As a new developer:
I would like to have installation instructions for easy onboarding

## Acceptance Criteria
* Installation instructions must be written and posted to GitHub

**Comment by yvanpdev** [comment]
added installation instruction on README

**Comment by cmenedes** [comment]
On my system, I need to run an Android emulator before writing the command 'react-native run-android'. I'll make note of that in the README. I have a command in the package.json to run the emulator, but will have to edit it if anyone else should be able to use it (it works with my folder structure currently).
